### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by Sebbe** [episerver/upgrade-assistant-extensions#10]
Hi,
I was having a look on this because I want to try to update our solution (nice weekend activity).
What I see is that the file [EPiServerPackageMap](https://github.com/episerver/upgrade-assistant-extensions/blob/main/src/EpiSourceUpdater/PackageMaps/EPiServerPackageMap.json)
has packages that doesn't exist or have been renamed. 

Will this be upgraded in tact with new preleases and/or releases?

**Comment by lunchin** [comment]
I updated the package maps to use * instead
