### ISSUE TITLE
Missing configs for CMS

### ISSUE THREAD

**Issue by LucGosso** [episerver/upgrade-assistant-extensions#13]
Suggestion, when someone has time:

would it be possible to add:

1. .ConfigureCmsDefaults() in program.cs
2. add ConnectionStrings to appsettings.json (port from web.config)
3. add ConfigureApplicationCookie to Startup.cs

For a smoother porting

**Comment by lunchin** [comment]
Connectionstrings should be ported by upgrade-assistant.  The others can update

**Comment by JohanPetersson** [comment]
Why is ConfigureApplicationCookie needed? Seems specific to your application and should not be needed.

**Comment by lunchin** [comment]
@LucGosso do you still want configure application cookie.  Seems the others were fixed with bug fix contribution we made a couple months ago.

**Comment by LucGosso** [comment]
nope, just suggestion, see ya
