### ISSUE TITLE
Error using v1.0.6

### ISSUE THREAD

**Issue by marijorg** [episerver/upgrade-assistant-extensions#14]
Tried running upgrade assistant with extension on a basic Alloy site. It fails on first step with error message:

PS C:\projects\alloytonet5\alloytest> upgrade-assistant upgrade alloytest.csproj --extension "C:\temp\EPi.Source.Updater.1.0.6" --ignore-unsupported-features
[08:34:40 INF] Loaded 6 extensions
[08:34:41 ERR] Unexpected error
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiAttributeRemoverAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiAttributeRemoverCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiClassReplacementsAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiClassReplacementsCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiObsoleteTypesAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiObsoleteTypesCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiObsoleteUsingAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiObsoleteUsingCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.FindUIConfigurationReplacementAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.FindUIConfigurationReplacementCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.DotNet.UpgradeAssistant.Extensions.ExtensionInstance.<>c.<AddServices>b__12_0(Assembly assembly) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Extensions/ExtensionInstance.cs:line 93
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.DotNet.UpgradeAssistant.Extensions.ExtensionInstance.AddServices(IServiceCollection services) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Extensions/ExtensionInstance.cs:line 98
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.<StartAsync>b__6_0(ContainerBuilder builder) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 55
   at Autofac.Core.Lifetime.LifetimeScope.CreateScopeRestrictedRegistry(Object tag, Action`1 configurationAction)
   at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action`1 configurationAction)
   at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Action`1 configurationAction)
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 50
System.TypeLoadException: Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiAttributeRemoverAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiAttributeRemoverCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiClassReplacementsAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiClassReplacementsCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiObsoleteTypesAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiObsoleteTypesCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.EpiObsoleteUsingAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.EpiObsoleteUsingCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_SupportedDiagnostics' in type 'Epi.Source.Updater.FindUIConfigurationReplacementAnalyzer' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'get_FixableDiagnosticIds' in type 'Epi.Source.Updater.FindUIConfigurationReplacementCodeFixProvider' from assembly 'Epi.Source.Updater, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by lunchin** [comment]
Thanks I upgraded the abstractions to the latest and added the dependent libraries to zip output.  Could you please try 1.0.7 and then close this if it fixes your issue

**Comment by marijorg** [comment]
Solved in v1.0.7. Closing issue.
