### ISSUE TITLE
Wrong framework version targeted

### ISSUE THREAD

**Issue by marijorg** [episerver/upgrade-assistant-extensions#20]
I've followed the instructions on how to set target framework for upgrade assistant: https://github.com/episerver/upgrade-assistant-extensions#using-the-extension
But I can see from log files that .NET 6 sdk is being used.... 

Setting env variable does not seem to work. 

![image](https://user-images.githubusercontent.com/2111786/148826014-09b2fd9e-fee6-4363-981c-5d8711ce6239.png)

**Comment by lunchin** [comment]
It will always use the latest version of msbuild because the tool is written in dotnet 6.  However it should set the correct version when updating the project file framework version,

**Comment by vyan024** [comment]
@marijorg 

If you have multiple versions of SDK installed and want to build with specific .NET5 SDK, you'll need to build your own version of upgrade-assistant instead. Please refer to Johan's blog post with more details.

https://world.optimizely.com/blogs/Johan-Bjornfot/Dates1/2022/1/upgrade-to-cms-12-updates-to-upgrade-assistant-extensions/

**Comment by marijorg** [comment]
Ok, closing issue.
